-- MySQL Script generated by MySQL Workbench
-- Thu Nov 10 18:37:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema rpg_2d
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rpg_2d` ;

-- -----------------------------------------------------
-- Schema rpg_2d
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rpg_2d` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Invetario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Invetario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Invetario` (
  `idinventario` INT NOT NULL,
  `iditem` INT NULL,
  `numslot` INT NULL,
  `nummaxacumulacion` INT NULL,
  `icono` VARCHAR(20) NULL,
  PRIMARY KEY (`idinventario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `item` (
  `iditem` INT NOT NULL,
  `nombre` VARCHAR(30) NULL,
  `icono` VARCHAR(20) NULL,
  `descripcion` VARCHAR(50) NULL,
  `tipo` VARCHAR(25) NULL,
  `consumible` VARCHAR(45) NULL,
  `acumulacionmax` INT NULL,
  `acumulable` INT NULL AUTO_INCREMENT,
  `personaje_idpersonaje` INT NOT NULL,
  `Invetario_idinventario` INT NOT NULL,
  PRIMARY KEY (`iditem`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `personaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `personaje` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `personaje` (
  `idpersonaje` INT NOT NULL,
  `idinventario` INT NULL,
  `idjugador` INT NULL,
  `nummaxenederro` INT NULL AUTO_INCREMENT,
  `misionescumplidas` INT NULL,
  `posx` POINT NULL,
  `posy` POINT NULL,
  `totaltiempojugado` DATETIME NULL,
  `Invetario_idinventario` INT NOT NULL,
  PRIMARY KEY (`idpersonaje`))
ENGINE = InnoDB;

SHOW WARNINGS;
USE `rpg_2d` ;

-- -----------------------------------------------------
-- Table `jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jugador` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jugador` (
  `idjugador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `correoelectronico` INT NOT NULL,
  `fecharegistro` DATE NULL,
  `contraseña` VARCHAR(20) NULL,
  `avatar` VARCHAR(20) NULL,
  `personaje_idpersonaje` INT NOT NULL,
  PRIMARY KEY (`idjugador`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
